# PostgreSQL. Versions 9.3 and up are supported.
# It is crucial to ensure that the PostgreSQL data directory has sufficient space to operate. Regularly check disk space with `df -h` and clean up unnecessary files or expand disk size as needed.
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["BASE_SOURCE_DATABASE_HOST"] || "localhost" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %> # Updated to "postgres" to resolve conflict
  port: 5432
  timeout: 5000 # Set a timeout value in milliseconds for connecting to the database server. Adjust as needed.

development: &development
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "base_source_development" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>

test:
  <<: *development
  database: <%= ENV.fetch("DATABASE_NAME") { "base_source_test" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "base_source_password") %> # Updated to "base_source_password" to resolve conflict

production:
  <<: *development
  database: <%= ENV.fetch("DATABASE_NAME") { "base_source_production" } %>
  username: <%= ENV["DATABASE_USERNAME"] || "base_source" %> # Kept "base_source" to resolve conflict
  password: <%= ENV.fetch("DATABASE_PASSWORD", "base_source_password") %> # Kept "base_source_password" to resolve conflict

staging:
  <<: *development
  database: <%= ENV.fetch("DATABASE_NAME") { "base_source_staging" } %>
  username: <%= ENV["DATABASE_USERNAME"] || "base_source" %> # Kept "base_source" to resolve conflict
  password: <%= ENV.fetch("DATABASE_PASSWORD", "base_source_password") %> # Kept "base_source_password" to resolve conflict
